# /flux/boot/traefik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: dev
spec:
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 9.2.7
      
  interval: 1m0s