apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: nginx
    releaseName: nginx
    valuesFile: values.yaml
    version: 13.1.6

