# /flux/boot/traefik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: dev
spec:
  chart:
    spec:
      chart: flux-ui
      sourceRef:
        kind: HelmRepository
        name: flux-ui
      version: 0.1.0
  interval: 1m0s