# /flux/boot/traefik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: dev
spec:
  chart:
    spec:
      chart: fluxcd-webui
      sourceRef:
        kind: HelmRepository
        name: ccowley
      version: 0.0.2
  interval: 1m0s